name: DiscuzReader
version: 0.1
description: Read threads from Discuz forums and display them in server
website: http://dev.bukkit.org/bukkit-plugins/DiscuzReader/
authors:
    - Trexguo
main: com.rainmc.plugins.DiscuzReader
commands:
    DiscuzReader:
        description: Various commands for DiscuzReader.
        usage: |
            /<command> help - Print help info.
            /<command> reload - reloads the configuration.
            /<command> off  - disable automatic broadcast.
            /<command> on - enable automatic broadcast.
            /<command> broadcast - Manually broadcast all cached posts.
            /<command> fetch - Manually fetch the latest posts from each areas.
        aliases: dr
permissions:
    discuzreader.*:
        description: Gives access to all Chairs commands
        children:
            discuzreader.on: true
            discuzreader.off: true
            discuzreader.reload: true
            discuzreader.broadcast: true
            discuzreader.fetch: true
    discuzreader.on:
        description: Allows you to enable automatic broadcast.
        default: true
    discuzreader.off:
        description: Allows you to disable automatic broadcast.
        default: true
    discuzreader.reload:
        description: Allows you to reload DiscuzReader configuration.
        default: op
    discuzreader.broadcast:
        description: Manually broadcast all cached posts.
        default: op
    discuzreader.fetch:
        description: Manually fetch the latest posts from each areas.
        default: op